#!/usr/bin/env node
import {loadFeedInput} from "./input.js";
import {platformResources,validateFeed,type FeedIssue,type FeedTarget,type FeedValidationResult} from "./engine.js";

const TARGETS:Record<string,FeedTarget>={wego:"wego",google:"google_hotel_center","google-hotel-center":"google_hotel_center",google_hotel_center:"google_hotel_center",trivago:"trivago",meta:"meta_catalog","meta-catalog":"meta_catalog",meta_catalog:"meta_catalog",criteo:"criteo",generic:"hotel_master_data","hotel-master-data":"hotel_master_data",hotel_master_data:"hotel_master_data"};

type Args={command:string;source?:string;flags:Map<string,string|boolean>};
function parseArgs(argv:string[]):Args{const command=argv[0]||"help";let source:string|undefined;const flags=new Map<string,string|boolean>();for(let i=1;i<argv.length;i++){const token=argv[i]!;if(token.startsWith("--")){const [name,inline]=token.slice(2).split("=",2);if(!name)continue;if(inline!==undefined){flags.set(name,inline);continue}const next=argv[i+1];if(next&&!next.startsWith("--")){flags.set(name,next);i++}else flags.set(name,true)}else if(source===undefined)source=token;else throw new Error(`Unexpected argument: ${token}`)}return{command,source,flags}}
function str(flags:Map<string,string|boolean>,name:string,def?:string){const v=flags.get(name);return typeof v==="string"?v:def}
function num(flags:Map<string,string|boolean>,name:string,def:number){const raw=str(flags,name);if(raw===undefined)return def;const v=Number(raw);if(!Number.isFinite(v)||v<=0)throw new Error(`--${name} must be a positive number.`);return v}
function target(value?:string){if(!value)throw new Error("Missing --target.");const resolved=TARGETS[value.toLowerCase()];if(!resolved)throw new Error(`Unknown target '${value}'.`);return resolved}
function targets(value?:string){if(!value)throw new Error("Missing --targets.");return value.split(",").map(x=>x.trim()).filter(Boolean).map(target)}
function threshold(flags:Map<string,string|boolean>){const v=(str(flags,"fail-on","error")||"error").toLowerCase();if(!["error","warning","none"].includes(v))throw new Error("--fail-on must be error, warning or none.");return v as "error"|"warning"|"none"}
function failed(issues:FeedIssue[],level:"error"|"warning"|"none"){if(level==="none")return false;if(level==="warning")return issues.some(i=>i.level==="error"||i.level==="warning");return issues.some(i=>i.level==="error")}
function print(result:FeedValidationResult){const errors=result.issues.filter(i=>i.level==="error");const warnings=result.issues.filter(i=>i.level==="warning");console.log(`${platformResources[result.target].title}\n\nFormat:  ${result.format}\nRecords: ${result.records}\nScore:   ${result.score}/100`);for(const [title,items] of [["Errors",errors],["Warnings",warnings]] as const){if(!items.length)continue;console.log(`\n${title}\n${"-".repeat(title.length)}`);for(const issue of items)console.log(`${issue.code}${issue.rows?.length?` (${issue.rows.length} rows)`:""}: ${issue.message}`)}if(!errors.length&&!warnings.length)console.log("\nNo errors or warnings detected.")}
function printCompare(results:FeedValidationResult[]){console.log("Target                         Score  Errors  Warnings  Records");console.log("---------------------------------------------------------------");for(const r of results){const e=r.issues.filter(i=>i.level==="error").length,w=r.issues.filter(i=>i.level==="warning").length;console.log(`${platformResources[r.target].title.slice(0,30).padEnd(30)} ${String(r.score).padStart(5)} ${String(e).padStart(7)} ${String(w).padStart(9)} ${String(r.records).padStart(8)}`)}}
function help(){console.log(`@metasearch/feed-validator\n\nUsage:\n  metasearch validate <file|url|-> --target <target> [options]\n  metasearch compare <file|url|-> --targets <a,b,c> [options]\n\nTargets: google-hotel-center, wego, trivago, meta, criteo, hotel-master-data\n\nOptions:\n  --format auto|csv|tsv|json|xml|ndjson\n  --output pretty|json\n  --fail-on error|warning|none\n  --timeout <ms>\n  --max-bytes <bytes>\n  --max-redirects <count>\n`)}

async function main(){const args=parseArgs(process.argv.slice(2));if(args.command==="help"||args.command==="--help"||args.flags.has("help")){help();return 0}if(!["validate","compare"].includes(args.command))throw new Error(`Unknown command '${args.command}'.`);if(!args.source)throw new Error("Missing input source. Provide a local file, HTTP(S) URL, or '-' for stdin.");const input=await loadFeedInput(args.source,{timeoutMs:num(args.flags,"timeout",15000),maxBytes:num(args.flags,"max-bytes",2000000),maxRedirects:num(args.flags,"max-redirects",3)});const format=str(args.flags,"format","auto");const output=(str(args.flags,"output","pretty")||"pretty").toLowerCase();if(!["pretty","json"].includes(output))throw new Error("--output must be pretty or json.");const failOn=threshold(args.flags);if(args.command==="validate"){const result=validateFeed(target(str(args.flags,"target")),input,format);if(output==="json")console.log(JSON.stringify(result,null,2));else print(result);return failed(result.issues,failOn)?1:0}const results=targets(str(args.flags,"targets")).map(t=>validateFeed(t,input,format));if(output==="json")console.log(JSON.stringify({results},null,2));else printCompare(results);return results.some(r=>failed(r.issues,failOn))?1:0}
main().then(code=>{process.exitCode=code}).catch(error=>{console.error(`metasearch: ${error instanceof Error?error.message:String(error)}`);process.exitCode=2});
