import {duplicateRows,getValue,hasValue,invalidCoordinateRows,parseDelimitedRecords,type FeedRecord} from "./core.js";

export type FeedTarget="wego"|"google_hotel_center"|"trivago"|"meta_catalog"|"criteo"|"hotel_master_data";
export type FeedFormat="JSON"|"XML"|"CSV"|"TSV"|"NDJSON";
export type FeedIssue={level:"error"|"warning"|"info";code:string;message:string;rows?:number[]};
export type FeedValidationResult={target:FeedTarget;format:FeedFormat;records:number;score:number;issues:FeedIssue[];coverage:Record<string,{present:number;missing:number}>};
export type CanonicalHotelRecord={sourceIndex:number;id?:unknown;name?:unknown;description?:unknown;address?:unknown;city?:unknown;province?:unknown;postalCode?:unknown;country?:unknown;phone?:unknown;latitude?:unknown;longitude?:unknown;link?:unknown;image?:unknown;price?:unknown;currency?:unknown;availability?:unknown;brand?:unknown;category?:unknown;starRating?:unknown;amenities?:unknown};
export type PlatformRequirement={field:string;label:string;level:"required"|"recommended"|"informational";formats?:FeedFormat[];note?:string};

export const feedTargets=["wego","google_hotel_center","trivago","meta_catalog","criteo","hotel_master_data"] as const satisfies readonly FeedTarget[];

const aliases={
  id:["id","hotel_id","property_id","item_id","product_id","offer_id","code","partner_reference"],
  name:["name","hotel_name","property_name","title","product_name"],description:["description","hotel_description","property_description","product_description","desc"],
  address:["address","property_address","street_address","addr1","street"],city:["city","city_name"],province:["province","state","region"],postal:["postal_code","postcode","zip","zip_code"],country:["country","country_code"],phone:["phone","telephone","phone_number"],
  latitude:["latitude","lat"],longitude:["longitude","lng","lon","long"],link:["link","url","website","web","hotel_url","landing_url","product_url"],image:["image","images","image_url","image_link","picture_url","photos"],price:["price","sale_price","base_price","amount"],currency:["currency","currency_code"],availability:["availability","status","stock"],brand:["brand","hotel_brand","chain","chain_name"],category:["category","product_type","property_type","google_product_category","accommodation type","accommodation_type"],star:["star_rating","stars","rating"],amenities:["amenities","facilities"]
} as const;

function parseJson(input:string):FeedRecord[]{const parsed=JSON.parse(input) as unknown;if(Array.isArray(parsed))return parsed as FeedRecord[];if(parsed&&typeof parsed==="object"){const object=parsed as FeedRecord;const array=["hotels","properties","items","products","listings","records"].map(k=>object[k]).find(Array.isArray)??Object.values(object).find(Array.isArray);return Array.isArray(array)?array as FeedRecord[]:[object]}throw new Error("No feed records found in JSON.")}
function parseNdjson(input:string):FeedRecord[]{const rows=input.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map((line,index)=>{try{const value=JSON.parse(line);if(value&&typeof value==="object"&&!Array.isArray(value))return value as FeedRecord}catch{}throw new Error(`Invalid NDJSON at line ${index+1}.`)});if(!rows.length)throw new Error("No feed records found in NDJSON.");return rows}
function xmlTag(block:string,tag:string){const match=block.match(new RegExp(`<${tag}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${tag}>`,"i"));return match?match[1]!.replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim():""}
function parseXml(input:string,target:FeedTarget):FeedRecord[]{const tags=target==="google_hotel_center"?["listing"]:target==="trivago"?["hotel"]:["hotel","property","item","product","entry","listing"];for(const tag of tags){const blocks=[...input.matchAll(new RegExp(`<${tag}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${tag}>`,"gi"))].map(m=>m[1]!);if(!blocks.length)continue;return blocks.map(block=>{const record:FeedRecord={};for(const field of ["id","partner_reference","name","description","desc","address","street","city","province","state","postal_code","postcode","country","phone","latitude","longitude","link","url","web","website","image","image_url","image_link","price","currency","availability","brand","hotel_brand","category","property_type","accommodation_type","star_rating","amenities"]){const value=xmlTag(block,field);if(value)record[field]=value}return record})}throw new Error("No feed records found in XML.")}
function looksLikeNdjson(input:string){const lines=input.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(lines.length<2)return false;try{return lines.slice(0,5).every(line=>{const v=JSON.parse(line);return v&&typeof v==="object"&&!Array.isArray(v)})}catch{return false}}

export function detectFeedFormat(content:string,hint?:string):FeedFormat{const input=content.trim();if(!input)throw new Error("Feed is empty.");const chosen=(hint||"").toLowerCase();const map:Record<string,FeedFormat>={json:"JSON",xml:"XML",csv:"CSV",tsv:"TSV",ndjson:"NDJSON",jsonl:"NDJSON"};if(chosen&&chosen!=="auto"&&map[chosen])return map[chosen];if(looksLikeNdjson(input))return"NDJSON";if(input.startsWith("{")||input.startsWith("["))return"JSON";if(input.startsWith("<"))return"XML";const first=input.split(/\r?\n/,1)[0]||"";return first.split("\t").length>first.split(",").length?"TSV":"CSV"}
export function parseFeed(content:string,target:FeedTarget,format?:string){const detected=detectFeedFormat(content,format);if(detected==="JSON")return{format:detected,rows:parseJson(content)};if(detected==="NDJSON")return{format:detected,rows:parseNdjson(content)};if(detected==="XML")return{format:detected,rows:parseXml(content,target)};const parsed=parseDelimitedRecords(content,detected==="TSV"?"\t":",");return{format:detected,rows:parsed.records}}
function rowsMissing(rows:FeedRecord[],names:readonly string[]){return rows.map((row,index)=>hasValue(getValue(row,names))?-1:index).filter(index=>index>=0)}
function validUrl(value:unknown){if(!hasValue(value))return false;try{return["http:","https:"].includes(new URL(String(Array.isArray(value)?value[0]:value)).protocol)}catch{return false}}
function addCoverage(rows:FeedRecord[]){return Object.fromEntries(Object.entries(aliases).map(([label,names])=>{const missing=rowsMissing(rows,names);return[label,{present:rows.length-missing.length,missing:missing.length}]}))}

export function normalizeHotelRecords(content:string,format?:string,target:FeedTarget="hotel_master_data"):{format:FeedFormat;records:CanonicalHotelRecord[]}{const parsed=parseFeed(content,target,format);return{format:parsed.format,records:parsed.rows.map((row,index)=>({sourceIndex:index,id:getValue(row,aliases.id),name:getValue(row,aliases.name),description:getValue(row,aliases.description),address:getValue(row,aliases.address),city:getValue(row,aliases.city),province:getValue(row,aliases.province),postalCode:getValue(row,aliases.postal),country:getValue(row,aliases.country),phone:getValue(row,aliases.phone),latitude:getValue(row,aliases.latitude),longitude:getValue(row,aliases.longitude),link:getValue(row,aliases.link),image:getValue(row,aliases.image),price:getValue(row,aliases.price),currency:getValue(row,aliases.currency),availability:getValue(row,aliases.availability),brand:getValue(row,aliases.brand),category:getValue(row,aliases.category),starRating:getValue(row,aliases.star),amenities:getValue(row,aliases.amenities)}))}}

export const platformResources:Record<FeedTarget,{title:string;description:string;formats:string[];mode:string;officialDocs?:string}>={
wego:{title:"Wego Hotel Feed",description:"Static hotel feed pre-check based on Wego's published hotel integration requirements.",formats:["JSON","XML","CSV"],mode:"published-contract",officialDocs:"https://developers.wego.com/docs/provider/hotels-integration-requirements/"},
google_hotel_center:{title:"Google Hotel Center Hotel List",description:"Static Hotel List pre-check for Google Hotel Center property inventory.",formats:["CSV","XML"],mode:"published-contract",officialDocs:"https://support.google.com/hotelprices/answer/9218458?hl=en"},
trivago:{title:"trivago FastConnect Hotel Data",description:"Hotel inventory feed pre-check based on trivago FastConnect's published Hotel Data contract.",formats:["CSV","JSON"],mode:"published-contract",officialDocs:"https://developer.trivago.com/fastconnect/hotel-data.html"},
meta_catalog:{title:"Meta Catalog Readiness",description:"Hotel/travel catalog mapping readiness pre-check.",formats:["JSON","XML","CSV","TSV"],mode:"readiness"},
criteo:{title:"Criteo Catalog Feed",description:"Catalog import and data-quality readiness pre-check.",formats:["JSON","XML","CSV","TSV"],mode:"readiness"},
hotel_master_data:{title:"Hotel Master Data",description:"Platform-independent hotel master-data quality audit.",formats:["JSON","XML","CSV","TSV","NDJSON"],mode:"generic-quality"}}

export const platformRequirements:Record<FeedTarget,PlatformRequirement[]>={
wego:[{field:"id",label:"Property ID",level:"required"},{field:"name",label:"Property Name",level:"required"},{field:"address",label:"Property Address",level:"required"},{field:"city",label:"City",level:"required"},{field:"country",label:"Country",level:"required"},{field:"latitude",label:"Latitude",level:"required"},{field:"longitude",label:"Longitude",level:"required"}],
google_hotel_center:[{field:"id",label:"Hotel ID",level:"required"},{field:"name",label:"Hotel name",level:"required"},{field:"country",label:"Country code",level:"required"},{field:"address",label:"Address",level:"required"},{field:"phone_or_geo",label:"Phone or latitude + longitude",level:"required"}],
trivago:[{field:"id",label:"partner_reference",level:"required"},{field:"name",label:"name",level:"required"},{field:"address",label:"address / street",level:"required"},{field:"postalCode",label:"postcode",level:"required"},{field:"city",label:"city",level:"required"},{field:"country",label:"country",level:"required"},{field:"category",label:"accommodation type",level:"required",formats:["CSV"]},{field:"starRating",label:"category / stars",level:"required",formats:["CSV"]},{field:"latitude",label:"latitude",level:"required"},{field:"longitude",label:"longitude",level:"required"}],
meta_catalog:[{field:"id",label:"Catalog ID",level:"required"},{field:"name",label:"Name/title",level:"recommended"},{field:"link",label:"Landing URL",level:"recommended"},{field:"image",label:"Image",level:"recommended"}],
criteo:[{field:"id",label:"Catalog ID",level:"required"},{field:"name",label:"Name/title",level:"recommended"},{field:"link",label:"Landing URL",level:"recommended"},{field:"image",label:"Image",level:"recommended"}],
hotel_master_data:[{field:"id",label:"ID",level:"required"},{field:"name",label:"Name",level:"required"},{field:"address",label:"Address",level:"required"},{field:"city",label:"City",level:"required"},{field:"country",label:"Country",level:"required"}]}

export function comparePlatformRequirements(targets:readonly FeedTarget[]=feedTargets){return targets.map(target=>({target,...platformResources[target],requirements:platformRequirements[target]}))}

export function validateFeed(target:FeedTarget,content:string,format?:string):FeedValidationResult{
 if(content.length>2_000_000)throw new Error("Feed exceeds the 2 MB validation limit.");
 const parsed=parseFeed(content,target,format);const rows=parsed.rows;const issues:FeedIssue[]=[];const duplicates=duplicateRows(rows,aliases.id);const badCoords=invalidCoordinateRows(rows,aliases.latitude,aliases.longitude);
 if(duplicates.length)issues.push({level:"error",code:"DUPLICATE_ID",message:`Duplicate IDs detected in ${duplicates.length} record(s).`,rows:duplicates});
 if(badCoords.length)issues.push({level:"error",code:"INVALID_COORDINATES",message:`Invalid or incomplete coordinates in ${badCoords.length} record(s).`,rows:badCoords});
 const req=(code:string,label:string,names:readonly string[],level:"error"|"warning"="error")=>{const missing=rowsMissing(rows,names);if(missing.length)issues.push({level,code,message:`${label} missing in ${missing.length}/${rows.length} record(s).`,rows:missing});return missing.length};
 let missing=0,total=Math.max(1,rows.length);
 if(target==="wego"){const fields:[[string,string,readonly string[]],...Array<[string,string,readonly string[]]>]=[["MISSING_ID","Property ID",aliases.id],["MISSING_NAME","Property name",aliases.name],["MISSING_ADDRESS","Address",aliases.address],["MISSING_CITY","City",aliases.city],["MISSING_COUNTRY","Country",aliases.country],["MISSING_LATITUDE","Latitude",aliases.latitude],["MISSING_LONGITUDE","Longitude",aliases.longitude]];total=Math.max(1,rows.length*fields.length);for(const f of fields)missing+=req(f[0],f[1],f[2])}
 else if(target==="google_hotel_center"){total=Math.max(1,rows.length*5);missing+=req("MISSING_ID","Hotel ID",aliases.id)+req("MISSING_NAME","Hotel name",aliases.name)+req("MISSING_COUNTRY","Country",aliases.country)+req("MISSING_ADDRESS","Address",aliases.address);const noContact=rows.map((r,i)=>hasValue(getValue(r,aliases.phone))||(hasValue(getValue(r,aliases.latitude))&&hasValue(getValue(r,aliases.longitude)))?-1:i).filter(i=>i>=0);missing+=noContact.length;if(noContact.length)issues.push({level:"error",code:"MISSING_PHONE_OR_GEO",message:`Phone or latitude+longitude missing in ${noContact.length}/${rows.length} record(s).`,rows:noContact})}
 else if(target==="trivago"){const fields=[["MISSING_ID","partner_reference",aliases.id],["MISSING_NAME","Hotel name",aliases.name],["MISSING_ADDRESS","Address",aliases.address],["MISSING_POSTCODE","Postcode",aliases.postal],["MISSING_CITY","City",aliases.city],["MISSING_COUNTRY","Country",aliases.country],["MISSING_LATITUDE","Latitude",aliases.latitude],["MISSING_LONGITUDE","Longitude",aliases.longitude]] as const;total=Math.max(1,rows.length*(fields.length+(parsed.format==="CSV"?2:0)));for(const f of fields)missing+=req(f[0],f[1],f[2]);if(parsed.format==="CSV"){missing+=req("MISSING_ACCOMMODATION_TYPE","Accommodation type",["accommodation type","accommodation_type","property_type"]);missing+=req("MISSING_CATEGORY","Hotel star category",["category","star_rating","stars"])}}
 else if(target==="hotel_master_data"){const fields=[["MISSING_ID","ID",aliases.id],["MISSING_NAME","Name",aliases.name],["MISSING_ADDRESS","Address",aliases.address],["MISSING_CITY","City",aliases.city],["MISSING_COUNTRY","Country",aliases.country]] as const;total=Math.max(1,rows.length*fields.length);for(const f of fields)missing+=req(f[0],f[1],f[2])}
 else{total=Math.max(1,rows.length*5);missing+=req("MISSING_ID","Catalog ID",aliases.id);missing+=req("MISSING_NAME","Name/title",aliases.name,"warning")+req("MISSING_LINK","Landing URL",aliases.link,"warning")+req("MISSING_IMAGE","Image",aliases.image,"warning")+req("MISSING_DESCRIPTION","Description",aliases.description,"warning");const badLinks=rows.map((r,i)=>{const v=getValue(r,aliases.link);return hasValue(v)&&!validUrl(v)?i:-1}).filter(i=>i>=0);if(badLinks.length)issues.push({level:"warning",code:"INVALID_URL",message:`Invalid landing URL in ${badLinks.length} record(s).`,rows:badLinks});issues.push({level:"info",code:"READINESS_ONLY",message:"This is a mapping/readiness pre-check, not official platform certification."})}
 const penalty=Math.min(25,duplicates.length*2+badCoords.length*2);const score=Math.max(0,Math.min(100,Math.round((total-missing)/total*100-penalty)));
 return{target,format:parsed.format,records:rows.length,score,issues,coverage:addCoverage(rows)}
}
